spring:
  application:
    name: user-management
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: password
    driver-class-name: org.postgresql.Driver
    username: keycloak
    url: jdbc:postgresql://localhost:5432/keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9082/realms/spring
          jwk-set-uri: http://localhost:9082/realms/spring/protocol/openid-connect/certs

server:
  port: 7171
  servlet:
    context-path: /auth
jwt:
  auth:
    converter:
      resource-id: spring-app
      principle-attribute: preferred_username


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  keycloak:
    admin:
      clientId: spring-app
      clientSecret: JPoHtIDzp9tF3hcOQq5LQRBX9C5TyzyI
    realm: spring
    serverUrl: http://localhost:9082


#for keycloak data not to be lost when abruptly terminated
quarkus:
  transaction-manager:
    enable-recovery: true
