spring:
  application:
    name: user-management
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: rootUser@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/oscaris?false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9082/realms/Oscaris
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 7171
  servlet:
    context-path: /auth

jwt:
  auth:
    converter:
      resource-id: oscaris-keycloak-demo-client
      principle-attribute: preferred_username


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  keycloak:
    admin:
      clientId: oscaris-keycloak-demo-client
      clientSecret: tx4UWmfXX3CkS8ymwvt5sH9A4aizUlAS
    realm: Oscaris
    serverUrl: http://localhost:9090


#for keycloak not to be lost when abruptly terminated
quarkus:
  transaction-manager:
    enable-recovery: true